Initial Parser
andyafter/Merlin pull request #4
Opened 2020-04-28 09:43 UTC by andyafter

2020-04-29 12:04 UTC, kelindar requested changes

2020-04-29 12:04 UTC, kelindar commented on merlin/json/metric_definitions.json
> +[
Let's do YAML instead

2020-05-12 03:55 UTC, kelindar approved these changes

2020-05-12 04:25 UTC, ocassetti commented on merlin/yaml/metric_definition.yml
> +id: test_metric
It is a list of metric definitions not just one

2020-05-12 04:25 UTC, ocassetti commented on merlin/parser.py
> +    def load_metrics(self, metric_db="merlin/yaml/metric_definition.yml"):
I don't think we need any defaults for metric_db

2020-05-12 04:25 UTC, ocassetti commented on merlin/parser.py
> +        self.metric_fields = set(['id', 'time', 'w_time', 'group_map', 'group_keys', 'func_map', 'func_expr', 'func_vars', 'compute_time', 'v_lvl', 'h_lvl', 'stages', 'description', 'version'])
I think you can figure out the fields from SoruceMetric... 
In any case `group_map` `group_keys` `func_map` will not be part of the source metric or definition

2020-05-15 14:14 UTC, ocassetti approved these changes

2020-05-17 14:47 UTC, merged